version: '3'
services:
  gateway:
    depends_on:
      - books
    build: ./gateway-service
    command: nodemon src/app.js
    ports:
      - "4000:4000"
    volumes:
      - ./gateway-service:/usr/src/app

  books:
    build: ./books-service
    command: nodemon src/app.js
    ports:
      - "4001:4001"
    volumes:
      - ./books-service:/usr/src/app

